import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "../components/navbar";
import UserAuth from "./auth/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          {/* <UserAuth /> */}
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
